@startuml UseCaseOverview

title Use Cases for Road Warrior

actor :traveller: as tr
actor :external person: as ep
actor :anaylst: as an
actor :help me agency: as hma
actor :travel system: as ts
actor :system: as sy

ep -[hidden]right- hma
ts -[hidden]right- hma
rectangle RoadWarior {
  together {
    usecase RIS as "register in systems \n..Requirements..\n"
    usecase lis as "login in system \n..Requirements..\n"
    usecase vd as "view dashboard \n..Requirements..\nFR6"
    usecase mr as "manage reservatioins \n..Requirements..\n FR6"
    usecase mt as "manage trip \n..Requirements..\n FR6"
    usecase stsn as "share trip via social networks \n..Requirements..\n FR7"
  }
  
  together {
    usecase patep as "provide access to external people \n..Requirements..\nFR7"
    usecase cmha as "configure help me! agency \n..Requirements..\nFR12"
    usecase ater as "access to end of year reports \n..Requirements..\nFR9"
    usecase dfawfe as "define filter and whitelist for email \n..Requirements..\nFR3"
    usecase coctha as "chat or call to help! agency \n..Requirements..\nFR12"
  }
  
  together {
    usecase atsti as "access to shared trip information \n..Requirements..\nFR7"
    usecase atar as "access to analytic reports \n..Requirements..\nFR10"
    usecase at as "analyse trends \n..Requirements..\nFR10"
  }
  
  together {
    usecase riauaht as "receive information about user and his trips \n..Requirements..\nFR12"
    usecase utd as "update travel data \n..Requirements..\nFR4"
    usecase rcocoefc as "recieve chats or calls or email from client \n..Requirements..\nFR12"
  }
  
  together {
    usecase pe as "poll emails \n..Requirements..\nFR2"
    usecase afawfe as "apply filter and whitelist for emails \n..Requirements..\nFR3"
    usecase pnacit as "push notification about changes in trip \n..Requirements..\nFR4"
    usecase rft as "remove finished trip \n..Requirements..\nFR6"
    usecase cad as "collect analytical data \n..Requirements..\nFR10"
  }
}

sy --> cad
sy --> rft
sy --> pnacit
sy --> afawfe
sy --> pe

tr --> RIS
tr --> lis
tr --> vd
tr --> mr
tr --> mt
tr --> stsn
tr --> patep
tr --> cmha
tr --> coctha
tr --> ater
tr --> dfawfe

ep --> atsti

an --> at
an --> atar

hma --> rcocoefc
hma --> riauaht

ts --> utd

'Include dependencies, so that they are not in a single line
RIS -[hidden]- patep
patep -[hidden]- atsti
atsti -[hidden]- riauaht 
riauaht -[hidden]- rft

@enduml
